from collections.abc import Generator
from typing import (
    Optional,
    Sequence,
)

xdg_data_home: str
xdg_data_dirs: Sequence[str]
xdg_config_home: str
xdg_config_dirs: Sequence[str]
xdg_cache_home: str
xdg_state_home: str

def save_config_path(*resource: str) -> str: ...
def save_data_path(*resource: str) -> str: ...
def save_cache_path(*resource: str) -> str: ...
def save_state_path(*resource: str) -> str: ...
def load_config_paths(*resource: str) -> Generator[str, None, None]: ...
def load_first_config(*resource: str) -> Optional[str]: ...
def load_data_paths(*resource: str) -> Generator[str, None, None]: ...
def get_runtime_dir(strict: bool = ...) -> str: ...
