from typing import (
    MutableMapping,
    Optional,
    Pattern,
    Sequence,
)

from xdg.Exceptions import ParsingError as ParsingError
from xdg.IniFile import IniFile as IniFile, is_ascii as is_ascii
from xdg.util import which as which

class DesktopEntry(IniFile):
    defaultGroup: str
    content: MutableMapping[str, MutableMapping[str, str]]
    def __init__(self, filename: Optional[str] = ...) -> None: ...
    def parse(self, file: str) -> None: ...
    def findTryExec(self) -> Optional[str]: ...
    def getType(self) -> str: ...
    def getVersion(self) -> float: ...
    def getVersionString(self) -> str: ...
    def getName(self) -> str: ...
    def getGenericName(self) -> str: ...
    def getNoDisplay(self) -> bool: ...
    def getComment(self) -> str: ...
    def getIcon(self) -> str: ...
    def getHidden(self) -> bool: ...
    def getOnlyShowIn(self) -> Sequence[str]: ...
    def getNotShowIn(self) -> Sequence[str]: ...
    def getTryExec(self) -> str: ...
    def getExec(self) -> str: ...
    def getPath(self) -> str: ...
    def getTerminal(self) -> bool: ...
    def getMimeType(self) -> Sequence[Pattern[str]]: ...
    def getMimeTypes(self) -> Sequence[str]: ...
    def getCategories(self) -> Sequence[str]: ...
    def getStartupNotify(self) -> bool: ...
    def getStartupWMClass(self) -> str: ...
    def getURL(self) -> str: ...
    def getServiceTypes(self) -> Sequence[str]: ...
    def getDocPath(self) -> str: ...
    def getKeywords(self) -> Sequence[str]: ...
    def getInitialPreference(self) -> str: ...
    def getDev(self) -> str: ...
    def getFSType(self) -> str: ...
    def getMountPoint(self) -> str: ...
    def getReadonly(self) -> bool: ...
    def getUnmountIcon(self) -> str: ...
    def getMiniIcon(self) -> str: ...
    def getTerminalOptions(self) -> str: ...
    def getDefaultApp(self) -> str: ...
    def getProtocols(self) -> Sequence[str]: ...
    def getExtensions(self) -> Sequence[str]: ...
    def getBinaryPattern(self) -> str: ...
    def getMapNotify(self) -> str: ...
    def getEncoding(self) -> str: ...
    def getSwallowTitle(self) -> str: ...
    def getSwallowExec(self) -> str: ...
    def getSortOrder(self) -> Sequence[str]: ...
    def getFilePattern(self) -> Pattern[str]: ...
    def getActions(self) -> Sequence[str]: ...
    filename: str
    def new(self, filename: str) -> None: ...
    type: str
    name: str
    def checkExtras(self) -> None: ...
    def checkGroup(self, group: str) -> None: ...
    def checkKey(self, key: str, value: str, group: str) -> None: ...
    def checkType(self, key: str, type: str) -> None: ...
    def checkOnlyShowIn(self, value: str) -> None: ...
    def checkCategories(self, value: str) -> None: ...
    def checkCategorie(self, value: str) -> None: ...
