from typing import (
    Any,
    Generator,
)

__all__ = ["CacheKeyError", "LRUCache", "DEFAULT_SIZE"]

DEFAULT_SIZE: int

class CacheKeyError(KeyError): ...

class LRUCache:
    class _Node:
        key: str
        obj: Any
        atime: float
        mtime: float
        def __init__(
            self, key: str, obj: Any, timestamp: float, sort_key: str
        ) -> None: ...
        def __lt__(self, other: Any) -> bool: ...
    size: int | None
    def __init__(self, size: int = ...) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __setitem__(self, key: str, obj: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Generator[str, None, None]: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def mtime(self, key: str) -> float: ...
