__all__ = ["DEFAULT_ENCODING", "RUNNING_UNDER_PY39_AND_UP", "FTPLIB_DEFAULT_ENCODING"]

RUNNING_UNDER_PY39_AND_UP: bool
FTPLIB_PY38_ENCODING: str
FTPLIB_PY39_ENCODING: str
DEFAULT_ENCODING: str
FTPLIB_DEFAULT_ENCODING: str
