from typing import (
    Any,
)

from .host import FTPHost

class _Path:
    basename: Any
    commonprefix: Any
    dirname: Any
    isabs: Any
    join: Any
    normcase: Any
    normpath: Any
    split: Any
    splitdrive: Any
    splitext: Any
    def __init__(self, host: FTPHost) -> None: ...
    def abspath(self, path: str) -> str: ...
    def exists(self, path: str) -> bool: ...
    def getmtime(self, path: str) -> float: ...
    def getsize(self, path: str) -> int: ...
    def isdir(self, path: str) -> bool: ...
    def isfile(self, path: str) -> bool: ...
    def islink(self, path: str) -> bool: ...
    def walk(self, top: str, func: Any, arg: Any) -> None: ...
