import os
from typing import (
    Optional,
)

from .stat import StatResult

class StatCache:
    max_age: Optional[float]
    def __init__(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def resize(self, new_size: int) -> None: ...
    def clear(self) -> None: ...
    def invalidate(self, path: str) -> None: ...
    def __getitem__(self, path: str) -> StatResult: ...
    def __setitem__(self, path: str, stat_result: StatResult) -> None: ...
    def __contains__(self, path: str) -> bool: ...
    def __len__(self) -> int: ...
